### ISSUE TITLE
not being able to scan all interfaces

### ISSUE THREAD

**Issue by imrehg** [resin-io/bonjour#3]
Scenario: wifi and eth both enabled, with device on eth. `rdt scan` does not find device, but taking down wifi results in the following error:

```
$rdt scan
dgram.js:438
    throw errnoException(err, 'addMembership');
    ^

Error: addMembership ENODEV
    at exports._errnoException (util.js:907:11)
    at Socket.addMembership (dgram.js:438:11)
    at Socket.<anonymous> (/home/greg/prog/nvm/versions/node/v4.6.1/lib/node_modules/resin-device-toolbox/node_modules/resin-sync/node_modules/resin-discoverable-services/node_modules/bonjour/node_modules/multicast-dns/index.js:52:14)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at startListening (dgram.js:121:10)
    at dgram.js:221:7
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
```

**Comment by hedss** [comment]
Please see resin-io-modules/resin-discoverable-services#10.
